import type { DashboardSummary } from "@/lib/insights";

export function DashboardOverview({ summary, currentLevel, targetLevel, learningPhase, dataError }: { summary: DashboardSummary | null; currentLevel: string; targetLevel: string | null; learningPhase: string; dataError: string | null }) {
  const stats = summary?.stats;
  const progress = stats && stats.total > 0 ? Math.round((stats.mastered / stats.total) * 100) : 0;
  return <div className="space-y-5">
    <section className="border-b border-line pb-5"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-medium text-brand-700">English Journey</p><h1 className="mt-2 text-2xl font-semibold text-ink-950">Dashboard</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-ink-600">学习、训练、复习和弱点记录会在这里汇总，帮助你持续看到自己的英语成长。</p></div><span className="w-fit rounded-md border border-line bg-white px-3 py-2 text-sm text-ink-600">{learningPhase}</span></div></section>
    {dataError && <p className="rounded-md border border-[#efc3bc] bg-[#fff5f3] px-3 py-2 text-sm text-[#9c3f31]">{dataError}</p>}
    <section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><StatusCard label="Current Level" value={currentLevel} /><StatusCard label="Target" value={targetLevel ?? "Not set"} /><StatusCard label="Mastery" value={`${progress}%`} /><StatusCard label="Study Streak" value={`${stats?.streak ?? 0} days`} /></section>
    <section className="grid gap-4 lg:grid-cols-[1.2fr_0.8fr]"><div className="rounded-lg border border-line bg-white p-5"><div className="flex items-center justify-between"><h2 className="text-base font-semibold text-ink-950">Today&apos;s Plan</h2><span className="rounded-md bg-brand-50 px-2 py-1 text-xs text-brand-700">{summary?.dueReviews ?? 0} due</span></div><div className="mt-5 grid gap-3 sm:grid-cols-3"><PlanItem label="Learn" value={`${Math.max(0, 5 - (stats?.started ?? 0))} words`} href="/learning" /><PlanItem label="Practice" value={`${stats?.incorrect ?? 0} errors`} href="/practice" /><PlanItem label="Review" value={`${summary?.dueReviews ?? 0} cards`} href="/review" /></div></div><div className="rounded-lg border border-line bg-white p-5"><h2 className="text-base font-semibold text-ink-950">Current Weakness</h2>{summary?.weaknesses[0] ? <div className="mt-5"><p className="text-lg font-semibold text-ink-950">{summary.weaknesses[0].dimension}</p><p className="mt-2 text-sm text-ink-600">错误率 {summary.weaknesses[0].score}% · {summary.weaknesses[0].evidence_count} 条证据</p><a href="/growth" className="mt-4 inline-block text-sm font-medium text-brand-700 hover:underline">查看成长分析</a></div> : <p className="mt-5 rounded-md border border-dashed border-line bg-panel p-4 text-sm leading-6 text-ink-600">完成训练后，这里会显示需要持续强化的方向。</p>}</div></section>
    <section className="rounded-lg border border-line bg-white p-5"><div className="flex items-center justify-between"><h2 className="text-base font-semibold text-ink-950">Recent Activity</h2><span className="text-xs text-ink-600">正确 {stats?.correct ?? 0} · 错误 {stats?.incorrect ?? 0}</span></div>{summary?.recentActivity.length ? <div className="mt-3 divide-y divide-line">{summary.recentActivity.slice(0, 5).map((item, index) => <div key={`${item.created_at}-${index}`} className="flex items-center justify-between gap-4 py-3 text-sm"><span className="text-ink-800">{item.term ?? "Dictionary item"}</span><span className={item.result === "correct" ? "text-brand-700" : "text-[#9c3f31]"}>{item.result === "correct" ? "Correct" : "Needs review"}</span></div>)}</div> : <p className="mt-4 rounded-md border border-dashed border-line bg-panel p-4 text-sm leading-6 text-ink-600">还没有学习记录。去 Learning 开始第一组内容。</p>}</section>
  </div>;
}

function StatusCard({ label, value }: { label: string; value: string }) { return <div className="rounded-lg border border-line bg-white p-5"><p className="text-sm text-ink-600">{label}</p><p className="mt-2 text-2xl font-semibold text-ink-950">{value}</p></div>; }
function PlanItem({ label, value, href }: { label: string; value: string; href: string }) { return <a href={href} className="rounded-md border border-line bg-panel p-4 hover:border-brand-600"><p className="text-sm font-medium text-ink-950">{label}</p><p className="mt-2 text-xs text-ink-600">{value}</p></a>; }
